/**
 * 开发预览服务器 —— 不开 DSH 也能单独调这个动画。
 *
 * 它用真实的 clientCss() / lib/client.js / assets/*.mp3 起一个最小页面，
 * 接口路径与宿主注册的完全一致，所以这里看到的就是 DSH 里会看到的。
 *
 * 用法: node tools/preview.mjs [端口]
 */

import { createServer } from 'node:http'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { clientCss, VOICES } from '../lib/index.js'

const PACKAGE_ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const PORT = Number(process.argv[2] ?? 5199)
const BASE = '/model-switch-fx'

/** 在线预览页的 SSE 连接。 */
const clients = new Set()

const frame = (payload) => `data: ${JSON.stringify(payload)}\n\n`
let seq = 0

function broadcast(id, opts = {}) {
  const token = `preview-${++seq}`
  const payload = frame({
    type: 'play',
    id,
    token,
    voice: VOICES[id],
    volume: opts.volume ?? 0.9,
    // 启动音开关与音量 —— 和宿主 lib/index.js 的 config 一致
    sfx: opts.sfx ?? true,
    sfxVolume: opts.sfxVolume ?? 0.5,
    // 复古未来音频链（同时作用于语音与启动音）
    fx: opts.fx ?? true,
  })
  for (const res of clients) {
    try {
      res.write(payload)
    } catch {
      clients.delete(res)
    }
  }
  console.log(`→ play ${id} (${VOICES[id]}s) token=${token}`
    + `${opts.sfx === 0 || opts.sfx === false ? ' sfx=off' : ''}`)
}

const PAGE = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>dsh-model-switch-fx preview</title>
<style>
${clientCss()}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;background:#0b0b12;color:#5b6172;
  font:13px/1.7 ui-monospace,Consolas,monospace}
.mock{padding:28px 32px;max-width:640px}
.mock h1{margin:0 0 6px;font-size:15px;color:#8b93a7;font-weight:600}
.mock p{margin:0 0 14px}
.bubble{background:#15161f;border:1px solid #23242f;border-radius:10px;padding:12px 14px;margin:0 0 10px}
.bar{position:fixed;left:50%;bottom:22px;transform:translateX(-50%);display:flex;gap:8px;flex-wrap:wrap;
  justify-content:center;z-index:10}
button{font:12px ui-monospace,Consolas,monospace;letter-spacing:.06em;cursor:pointer;
  padding:8px 14px;border-radius:6px;border:1px solid #2e3040;background:#171922;color:#9aa3b8}
button:hover{border-color:#4a4f68;color:#dfe4f0}
#log{position:fixed;left:16px;bottom:22px;font-size:11px;color:#454b5e;max-width:280px}
</style>
</head>
<body>
<div class="mock">
  <h1>模拟界面（动画期间应保持可见、可点）</h1>
  <div class="bubble">上下文注入 · model-selection · a/b → c/d</div>
  <div class="bubble">[model changed: assistant turns above this point were generated by …]</div>
  <p>点下面的按钮触发对应的角色动画。</p>
</div>
<div class="bar">
  ${Object.keys(VOICES).map(id => `<button data-id="${id}">${id}</button>`).join('\n  ')}
</div>
<div id="log">等待触发…</div>

<script src="${BASE}/client.js"></script>
<script>
var log = document.getElementById('log')
document.querySelectorAll('button').forEach(function (b) {
  b.addEventListener('click', function () {
    log.textContent = 'trigger: ' + b.dataset.id
    fetch('/trigger?id=' + encodeURIComponent(b.dataset.id)).catch(function () {})
  })
})
// 观察 client.js 是否回报了 done
var origFetch = window.fetch
window.fetch = function (url, opts) {
  if (String(url).indexOf('${BASE}/done') === 0) log.textContent = '已回报 done → 宿主可以放行请求'
  return origFetch.apply(this, arguments)
}
</script>
</body>
</html>`

const server = createServer((req, res) => {
  const url = new URL(req.url ?? '/', `http://localhost:${PORT}`)
  const path = url.pathname

  if (path === '/') {
    res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' })
    res.end(PAGE)
    return
  }

  if (path === '/trigger') {
    const id = url.searchParams.get('id')
    if (id !== null && Object.prototype.hasOwnProperty.call(VOICES, id)) {
      const sfxParam = url.searchParams.get('sfx')
      const volParam = url.searchParams.get('sfxVolume')
      broadcast(id, {
        // sfx=0 用来测「关掉启动音时一个节点都不排」
        sfx: sfxParam === null ? true : sfxParam !== '0' && sfxParam !== 'false',
        sfxVolume: volParam === null ? 0.5 : Number(volParam),
      })
    }
    res.writeHead(204)
    res.end()
    return
  }

  if (path === `${BASE}/events`) {
    res.writeHead(200, {
      'content-type': 'text/event-stream',
      'cache-control': 'no-cache',
      connection: 'keep-alive',
    })
    res.write(': connected\n\n')
    clients.add(res)
    res.on('close', () => clients.delete(res))
    return
  }

  if (path === `${BASE}/client.js`) {
    const body = readFileSync(join(PACKAGE_ROOT, 'lib', 'client.js'))
    res.writeHead(200, {
      'content-type': 'application/javascript; charset=utf-8',
      'content-length': String(body.length),
    })
    res.end(body)
    return
  }

  if (path === `${BASE}/done`) {
    console.log(`← done ${url.searchParams.get('token')}`)
    res.writeHead(204)
    res.end()
    return
  }

  const voice = /^\/model-switch-fx\/voice\/([a-z0-9-]+)\.mp3$/.exec(path)
  if (voice !== null && Object.prototype.hasOwnProperty.call(VOICES, voice[1])) {
    const body = readFileSync(join(PACKAGE_ROOT, 'assets', `${voice[1]}.mp3`))
    res.writeHead(200, { 'content-type': 'audio/mpeg', 'content-length': String(body.length) })
    res.end(body)
    return
  }

  // 其余包内资源统一从 assets/ 取 —— 加新资源时不用再改这里
  // （宿主半边在 lib/index.js 里按各自的路由提供，两边保持一致）
  const assset = /^\/model-switch-fx\/([a-z0-9_-]+\.(?:png|wav|jpg|webp))$/.exec(path)
  if (assset !== null) {
    const type = { png: 'image/png', wav: 'audio/wav', jpg: 'image/jpeg', webp: 'image/webp' }
    try {
      const body = readFileSync(join(PACKAGE_ROOT, 'assets', assset[1]))
      res.writeHead(200, {
        'content-type': type[assset[1].split('.').pop()] ?? 'application/octet-stream',
        'content-length': String(body.length),
      })
      res.end(body)
    } catch {
      res.writeHead(404, { 'content-type': 'text/plain; charset=utf-8' })
      res.end('asset not found')
    }
    return
  }

  res.writeHead(404, { 'content-type': 'text/plain; charset=utf-8' })
  res.end('not found')
})

server.listen(PORT, '127.0.0.1', () => {
  console.log(`preview: http://127.0.0.1:${PORT}/`)
})
